# Generated by Django 2.1.1 on 2018-09-08 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Title')),
                ('slug', models.CharField(max_length=120, unique=True, verbose_name='Slug')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Last update')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('icon', models.CharField(default='dashboard', max_length=60, verbose_name='Icon')),
                ('altair', models.BooleanField(default=False, verbose_name='Use the Altair rendering engine')),
                ('bokeh', models.BooleanField(default=True, verbose_name='Use the Bokeh rendering engine')),
                ('chartjs', models.BooleanField(default=False, verbose_name='Use the Chartjs rendering engine')),
                ('custom_content', models.BooleanField(default=False, verbose_name='Use custom content template')),
                ('custom_header', models.BooleanField(default=False, verbose_name='Use custom header template')),
                ('navbar_class', models.CharField(blank=True, max_length=120, verbose_name='Bulma nabvar css class')),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Authorized groups')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
            },
        ),
        migrations.CreateModel(
            name='DashboardView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Title')),
                ('slug', models.CharField(max_length=120, unique=True, verbose_name='Slug')),
                ('active', models.BooleanField(default=False, verbose_name='Active view')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='chartflo.Dashboard', verbose_name='Dashboard')),
            ],
            options={
                'verbose_name': 'View',
                'verbose_name_plural': 'Views',
            },
        ),
    ]
