# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('slug', models.CharField(max_length=120, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name_plural': 'Dashboards',
                'verbose_name': 'Dashboard',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
            ],
            options={
                'verbose_name_plural': 'Filters',
                'verbose_name': 'Filter',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('app', models.CharField(max_length=120, verbose_name='App')),
                ('model', models.CharField(max_length=120, verbose_name='Model')),
            ],
            options={
                'verbose_name_plural': 'Queries',
                'verbose_name': 'Query',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('html', models.TextField(blank=True, verbose_name='Html')),
                ('script', models.TextField(blank=True, verbose_name='Script')),
                ('chart_type', models.CharField(choices=[('bar', 'Bar'), ('line', 'Line'), ('scatter', 'Scatter')], default='bar', max_length=120, verbose_name='Chart type')),
                ('width', models.PositiveSmallIntegerField(default=1200, verbose_name='Width')),
                ('height', models.PositiveSmallIntegerField(default=400, verbose_name='Height')),
                ('queries', models.ManyToManyField(related_name='questions', to='chartflo.Query', verbose_name='Queries')),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'verbose_name': 'Question',
            },
        ),
        migrations.AddField(
            model_name='filter',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='chartflo.Query', verbose_name='Query'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='questions',
            field=models.ManyToManyField(related_name='dashboards', to='chartflo.Question', verbose_name='Questions'),
        ),
    ]
