# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    replaces = [('chartflo', '0001_initial'), ('chartflo', '0002_auto_20170905_1212'), ('chartflo', '0003_auto_20170905_1236'), ('chartflo', '0004_question_json'), ('chartflo', '0005_auto_20170905_1247'), ('chartflo', '0006_auto_20170905_1446'), ('chartflo', '0007_question_timeseries'), ('chartflo', '0008_auto_20170905_1506'), ('chartflo', '0009_auto_20170906_1105'), ('chartflo', '0010_auto_20170907_0758'), ('chartflo', '0011_auto_20170907_0816'), ('chartflo', '0012_auto_20170907_0958')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('slug', models.CharField(max_length=120, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('app', models.CharField(max_length=120, verbose_name='App')),
                ('model', models.CharField(max_length=120, verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('html', models.TextField(blank=True, verbose_name='Html')),
                ('chart_type', models.CharField(choices=[('bar', 'Bar'), ('line', 'Line'), ('circle', 'Circle'), ('point', 'Point'), ('square', 'Square'), ('tick', 'Tick'), ('text', 'Text')], default='bar', max_length=120, verbose_name='Chart type')),
                ('width', models.PositiveSmallIntegerField(blank=True, default=800, verbose_name='Width')),
                ('height', models.PositiveSmallIntegerField(blank=True, default=300, verbose_name='Height')),
                ('queries', models.ManyToManyField(to='chartflo.Query', verbose_name='Queries')),
                ('color', models.CharField(blank=True, max_length=120, verbose_name='Color field')),
                ('x_field', models.CharField(default='', max_length=120, verbose_name='X axis field name')),
                ('x_field_type', models.CharField(default='', help_text="Ex: 'number:Q' to declare a quantitative field", max_length=120, verbose_name='X axis field type')),
                ('y_field', models.CharField(default='', max_length=120, verbose_name='Y axis field name')),
                ('y_field_type', models.CharField(default='', help_text="Ex: 'number:Q' to declare a quantitative field", max_length=120, verbose_name='Y axis field type')),
                ('json', django_extensions.db.fields.json.JSONField(blank=True, default=dict, verbose_name='Vega Lite encoded json data')),
                ('time_unit', models.CharField(blank=True, max_length=120, verbose_name='Time unit')),
                ('size', models.CharField(blank=True, max_length=120, verbose_name='Size field')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.AddField(
            model_name='dashboard',
            name='questions',
            field=models.ManyToManyField(blank=True, to='chartflo.Question', verbose_name='Questions'),
        ),
        migrations.AddField(
            model_name='query',
            name='filters',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Filters'),
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('html', models.TextField(blank=True, verbose_name='Html')),
                ('json', django_extensions.db.fields.json.JSONField(blank=True, default=dict, verbose_name='Vega Lite encoded json data')),
                ('slug', models.CharField(max_length=120, unique=True, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Chart',
                'verbose_name_plural': 'Charts',
            },
        ),
        migrations.AddField(
            model_name='dashboard',
            name='charts',
            field=models.ManyToManyField(blank=True, to='chartflo.Chart', verbose_name='Charts'),
        ),
    ]
