# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='extra_html',
            field=models.TextField(blank=True, verbose_name='Extra html'),
        ),
    ]
