# Generated by Django 2.1.1 on 2018-09-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardview',
            options={'ordering': ['order'], 'verbose_name': 'View', 'verbose_name_plural': 'Views'},
        ),
        migrations.AddField(
            model_name='dashboardview',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
