# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='altair',
            field=models.BooleanField(default=False, verbose_name='Use the Altair rendering engine'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='bokeh',
            field=models.BooleanField(default=True, verbose_name='Use the Bokeh rendering engine'),
        ),
    ]
