# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 09:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='name',
        ),
        migrations.AddField(
            model_name='chart',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 15, 9, 45, 12, 323993), verbose_name='Last update'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='number',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 15, 9, 45, 14, 610393), verbose_name='Last update'),
            preserve_default=False,
        ),
    ]
