# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chart_type',
            field=models.CharField(choices=[('Bar', 'bar'), ('Line', 'line'), ('Scatter', 'scatter')], default='Bar', max_length=120, verbose_name='Chart type'),
        ),
        migrations.AddField(
            model_name='question',
            name='height',
            field=models.PositiveSmallIntegerField(default=400, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='question',
            name='width',
            field=models.PositiveSmallIntegerField(default=1200, verbose_name='Width'),
        ),
    ]
