# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='query',
        ),
        migrations.AddField(
            model_name='query',
            name='filters',
            field=models.CharField(default='', max_length=255, verbose_name='Filters'),
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
