# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='chartjs',
            field=models.BooleanField(default=True, verbose_name='Use the Chartjs rendering engine'),
        ),
    ]
