# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='generator',
            field=models.CharField(blank=True, max_length=120, verbose_name='Generator'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='modelnames',
            field=models.CharField(blank=True, help_text='List of model names: ex: User,Group', max_length=200, verbose_name='Associated models'),
        ),
        migrations.AlterField(
            model_name='number',
            name='generator',
            field=models.CharField(blank=True, max_length=120, verbose_name='Generator'),
        ),
        migrations.AlterField(
            model_name='number',
            name='modelnames',
            field=models.CharField(blank=True, help_text='List of model names: ex: User,Group', max_length=200, verbose_name='Associated models'),
        ),
    ]
