# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='json',
            field=models.TextField(blank=True, verbose_name='Vega Lite encoded json data'),
        ),
    ]
