# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0002_chart_extra_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='extra_html',
        ),
        migrations.AddField(
            model_name='chart',
            name='html_after',
            field=models.TextField(blank=True, verbose_name='Html after'),
        ),
        migrations.AddField(
            model_name='chart',
            name='html_before',
            field=models.TextField(blank=True, verbose_name='Html before'),
        ),
    ]
