# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0002_auto_20170921_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='thresholds',
            field=models.CharField(blank=True, max_length=255, verbose_name='Thresholds'),
        ),
    ]
