# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0002_auto_20171127_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart',
        ),
        migrations.DeleteModel(
            name='Number',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='generators',
            field=models.CharField(default='mqueue', help_text='List of apps: ex: mqueue,myapp', max_length=255, verbose_name='Generators used by this dashboard'),
            preserve_default=False,
        ),
    ]
