# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0002_auto_20170905_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='color',
            field=models.CharField(blank=True, max_length=120, verbose_name='Color field'),
        ),
        migrations.AddField(
            model_name='question',
            name='x_field',
            field=models.CharField(default='', max_length=120, verbose_name='X axis field name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='x_field_type',
            field=models.CharField(default='', help_text="Ex: 'number:Q' to declare a quantitative field", max_length=120, verbose_name='X axis field type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='y_field',
            field=models.CharField(default='', max_length=120, verbose_name='Y axis field name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='y_field_type',
            field=models.CharField(default='', help_text="Ex: 'number:Q' to declare a quantitative field", max_length=120, verbose_name='Y axis field type'),
            preserve_default=False,
        ),
    ]
