# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0003_auto_20170911_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('slug', models.CharField(max_length=120, unique=True, verbose_name='Slug')),
                ('value', models.IntegerField(verbose_name='Value')),
                ('unit', models.CharField(blank=True, max_length=120, verbose_name='Unit')),
                ('html', models.TextField(blank=True, verbose_name='Html before')),
            ],
            options={
                'verbose_name': 'Number',
                'verbose_name_plural': 'Numbers',
            },
        ),
        migrations.AlterField(
            model_name='chart',
            name='slug',
            field=models.CharField(db_index=True, max_length=120, unique=True, verbose_name='Slug'),
        ),
    ]
