# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('chartflo', '0003_number_thresholds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=120, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=160, verbose_name='Title')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Last update')),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Authorized groups')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
            },
        ),
    ]
