# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 12:45
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0003_auto_20170905_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='json',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, verbose_name='Vega Lite encoded json data'),
        ),
    ]
