# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0004_auto_20170911_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Value'),
        ),
    ]
