# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0005_auto_20170911_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='legend',
            field=models.CharField(blank=True, max_length=120, verbose_name='Legend'),
        ),
        migrations.AlterField(
            model_name='number',
            name='html',
            field=models.TextField(blank=True, verbose_name='Html'),
        ),
    ]
