# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0005_auto_20170905_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='filters',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Filters'),
        ),
    ]
