# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0006_auto_20170905_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='timeseries',
            field=models.BooleanField(default=False, verbose_name='Is a timeserie'),
        ),
    ]
