# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0007_question_timeseries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='timeseries',
        ),
        migrations.AddField(
            model_name='question',
            name='time_unit',
            field=models.CharField(blank=True, max_length=120, verbose_name='Time unit'),
        ),
    ]
