# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartflo', '0008_auto_20170905_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='size',
            field=models.CharField(blank=True, max_length=120, verbose_name='Size field'),
        ),
        migrations.AlterField(
            model_name='question',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'Bar'), ('line', 'Line'), ('circle', 'Circle'), ('point', 'Point'), ('square', 'Square')], default='bar', max_length=120, verbose_name='Chart type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, default=300, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='question',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, default=800, verbose_name='Width'),
        ),
    ]
